feat: Make yamq dependency-free
kivra/yamq pull request #9
Opened 2021-10-15 11:10 UTC by moritzploss-k

## About

Since more and more applications are moving away from `lager` and `stdlib2`, it's nice to have a dependency-free version of `gen_lb`. I'm also adding a GitHub actions CI flow, and `rebar3` support.

2021-10-19 16:06 UTC, maxno-kivra requested changes
I love that you're ripping out stdlib2. About time I say. 

I just have one small nitpick, then this is good to go.

(One could argue to change all `s2_lisits:assoc` to `lists:keyfind` but I get that you want to minimize the diff and that's a very good argument)

2021-10-19 16:06 UTC, maxno-kivra commented on src/gen_lb.erl
> +  end.
I prefer self describing variable names, aka not shorten. The one I found most confusing of these is `Def`, first I read `Definition` and the. `Default`. Please expand these, we can afford the extra bytes 😉

2021-10-19 16:06 UTC, maxno-kivra commented on src/yamq.erl
> +  end.
Same as for the other `assoc`. I would love to see unambiguous variable names.

2021-10-21 14:25 UTC, moritzploss-k commented on src/yamq.erl
> +  end.
sure, will change that! It was literally a copy-paste from stdlib2, but you're right, I should have given it some extra love

2021-10-22 14:37 UTC, maxno-kivra approved these changes
🚀

2021-10-22 14:52 UTC, merged